# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceDetails'),
            preserve_default=False,
        ),
    ]
