# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200314_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetails',
            old_name='ammendments',
            new_name='amendments',
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='delivery_time',
            field=models.IntegerField(choices=[(30, '30'), (28, '28'), (21, '21'), (14, '14'), (7, '7'), (3, '3')], default=20),
        ),
    ]
