# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200321_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='amendments',
            field=models.CharField(choices=[(3, 3), (5, 5), (7, 7), ('NA', 'Not Applicable')], default='NA', max_length=254),
        ),
    ]
