# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200321_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='amendments',
            field=models.CharField(choices=[(3, 3), (5, 5), (7, 7), ('NA', 'Not Applicable')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='delivery_time',
            field=models.CharField(choices=[('30 Days', '30 Days'), ('28 Days', '28 Days'), ('21 Days', '21 Days'), ('14 Days', '14 Days'), ('7 Days', '7 Days'), ('3 Days', '3 Days'), ('NA', 'Not Applicable')], default='', max_length=254),
        ),
    ]
