# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200321_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
