# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicedetails_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='amendments',
            field=models.CharField(choices=[('Amemdments: 3', '3'), ('Amemdments: 5', '5'), ('Amemdments: 7', '7'), (' ', ' ')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='delivery_time',
            field=models.CharField(choices=[('Delivery Time: 30 Days', '30 Days'), ('Delivery Time: 28 Days', '28 Days'), ('Delivery Time: 21 Days', '21 Days'), ('Delivery Time: 14 Days', '14 Days'), ('Delivery Time: 7 Days', '7 Days'), ('Delivery Time: 3 Days', '3 Days'), (' ', ' ')], default='', max_length=254),
        ),
    ]
