# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20200321_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='plan_image',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
